<?php
/**
 * TransferServiceBooking
 *
 * PHP version 5
 *
 * @category Class
 * @package  EmanuelBuss\ApitudeTransfer
 * @author   Emanuel Karlsson <emanuel.karlsson@rolfsbuss.se>
 * @link     https://github.com/emanuelbuss/apitudetransfer
 */

/**
 * Transfer Booking API
 *
 * # APItude Transfer Booking API  APItude also includes now the ability to book transfers. This API will provide you with availability for transfer services and allow you to distribute those not only through the websites but also is thought to support mobile and tablets.  APItude for transfers API is designed to provide Hotelbeds Group clients with a set of API calls to:   * Enable the construction or creation of a complete transfer website or mobile application (app) * Integrate transfer services into existing systems both internal and external. * Integrate transfers contents for transfers into a common CMS for all the products being distributed.  **Transfer Booking API** provides all the needed calls (operations) to develop your booking funnel, confirm a booking and obtain the relevant information for a customer to enjoy the transfer service that he or she bought.  To obtain and cache the static content you can use [Transfers Cache API](), an API designed to return all the static information needed to operate the Transfers BookingAPI as quickly and simple as possible.
 *
 * OpenAPI spec version: 1.0
 * Contact: integrations.btb@hotelbeds.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/emanuelbuss/apitudetransfer
 * Do not edit the class manually.
 */

namespace EmanuelBuss\ApitudeTransfer\Model;

use \ArrayAccess;
use \EmanuelBuss\ApitudeTransfer\ObjectSerializer;

/**
 * TransferServiceBooking Class Doc Comment
 *
 * @category Class
 * @description The Transfer Service superclass
 * @package  EmanuelBuss\ApitudeTransfer
 * @author   Emanuel Karlsson <emanuel.karlsson@rolfsbuss.se>
 * @link     https://github.com/emanuelbuss/apitudetransfer
 */
class TransferServiceBooking implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TransferServiceBooking';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'arrival_flight_number' => 'string',
'arrival_ship_name' => 'string',
'arrival_train_info' => '\EmanuelBuss\ApitudeTransfer\Model\TrainInfo',
'cancellation_policies' => '\EmanuelBuss\ApitudeTransfer\Model\CancellationPolicy[]',
'category' => '\EmanuelBuss\ApitudeTransfer\Model\Category',
'content' => '\EmanuelBuss\ApitudeTransfer\Model\TransferServiceContent',
'departure_flight_number' => 'string',
'departure_ship_name' => 'string',
'departure_train_info' => '\EmanuelBuss\ApitudeTransfer\Model\TrainInfo',
'factsheet_id' => 'int',
'id' => 'int',
'links' => '\EmanuelBuss\ApitudeTransfer\Model\Link[]',
'paxes' => '\EmanuelBuss\ApitudeTransfer\Model\Pax[]',
'pickup_information' => '\EmanuelBuss\ApitudeTransfer\Model\PickupInformation',
'price' => '\EmanuelBuss\ApitudeTransfer\Model\Price',
'rate_key' => 'string',
'source_market_emergency_number' => 'string',
'status' => 'string',
'transfer_details' => '\EmanuelBuss\ApitudeTransfer\Model\TransferDetail[]',
'transfer_type' => 'string',
'vehicle' => '\EmanuelBuss\ApitudeTransfer\Model\Vehicle'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'arrival_flight_number' => null,
'arrival_ship_name' => null,
'arrival_train_info' => null,
'cancellation_policies' => null,
'category' => null,
'content' => null,
'departure_flight_number' => null,
'departure_ship_name' => null,
'departure_train_info' => null,
'factsheet_id' => 'int32',
'id' => 'int32',
'links' => null,
'paxes' => null,
'pickup_information' => null,
'price' => null,
'rate_key' => null,
'source_market_emergency_number' => null,
'status' => null,
'transfer_details' => null,
'transfer_type' => null,
'vehicle' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'arrival_flight_number' => 'arrivalFlightNumber',
'arrival_ship_name' => 'arrivalShipName',
'arrival_train_info' => 'arrivalTrainInfo',
'cancellation_policies' => 'cancellationPolicies',
'category' => 'category',
'content' => 'content',
'departure_flight_number' => 'departureFlightNumber',
'departure_ship_name' => 'departureShipName',
'departure_train_info' => 'departureTrainInfo',
'factsheet_id' => 'factsheetId',
'id' => 'id',
'links' => 'links',
'paxes' => 'paxes',
'pickup_information' => 'pickupInformation',
'price' => 'price',
'rate_key' => 'rateKey',
'source_market_emergency_number' => 'sourceMarketEmergencyNumber',
'status' => 'status',
'transfer_details' => 'transferDetails',
'transfer_type' => 'transferType',
'vehicle' => 'vehicle'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'arrival_flight_number' => 'setArrivalFlightNumber',
'arrival_ship_name' => 'setArrivalShipName',
'arrival_train_info' => 'setArrivalTrainInfo',
'cancellation_policies' => 'setCancellationPolicies',
'category' => 'setCategory',
'content' => 'setContent',
'departure_flight_number' => 'setDepartureFlightNumber',
'departure_ship_name' => 'setDepartureShipName',
'departure_train_info' => 'setDepartureTrainInfo',
'factsheet_id' => 'setFactsheetId',
'id' => 'setId',
'links' => 'setLinks',
'paxes' => 'setPaxes',
'pickup_information' => 'setPickupInformation',
'price' => 'setPrice',
'rate_key' => 'setRateKey',
'source_market_emergency_number' => 'setSourceMarketEmergencyNumber',
'status' => 'setStatus',
'transfer_details' => 'setTransferDetails',
'transfer_type' => 'setTransferType',
'vehicle' => 'setVehicle'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'arrival_flight_number' => 'getArrivalFlightNumber',
'arrival_ship_name' => 'getArrivalShipName',
'arrival_train_info' => 'getArrivalTrainInfo',
'cancellation_policies' => 'getCancellationPolicies',
'category' => 'getCategory',
'content' => 'getContent',
'departure_flight_number' => 'getDepartureFlightNumber',
'departure_ship_name' => 'getDepartureShipName',
'departure_train_info' => 'getDepartureTrainInfo',
'factsheet_id' => 'getFactsheetId',
'id' => 'getId',
'links' => 'getLinks',
'paxes' => 'getPaxes',
'pickup_information' => 'getPickupInformation',
'price' => 'getPrice',
'rate_key' => 'getRateKey',
'source_market_emergency_number' => 'getSourceMarketEmergencyNumber',
'status' => 'getStatus',
'transfer_details' => 'getTransferDetails',
'transfer_type' => 'getTransferType',
'vehicle' => 'getVehicle'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STATUS_CONFIRMED = 'CONFIRMED';
const STATUS_CANCELLED = 'CANCELLED';
const STATUS_MODIFIED = 'MODIFIED';
const TRANSFER_TYPE__PRIVATE = 'PRIVATE';
const TRANSFER_TYPE_SHARED = 'SHARED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CONFIRMED,
self::STATUS_CANCELLED,
self::STATUS_MODIFIED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransferTypeAllowableValues()
    {
        return [
            self::TRANSFER_TYPE__PRIVATE,
self::TRANSFER_TYPE_SHARED,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['arrival_flight_number'] = isset($data['arrival_flight_number']) ? $data['arrival_flight_number'] : null;
        $this->container['arrival_ship_name'] = isset($data['arrival_ship_name']) ? $data['arrival_ship_name'] : null;
        $this->container['arrival_train_info'] = isset($data['arrival_train_info']) ? $data['arrival_train_info'] : null;
        $this->container['cancellation_policies'] = isset($data['cancellation_policies']) ? $data['cancellation_policies'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;
        $this->container['departure_flight_number'] = isset($data['departure_flight_number']) ? $data['departure_flight_number'] : null;
        $this->container['departure_ship_name'] = isset($data['departure_ship_name']) ? $data['departure_ship_name'] : null;
        $this->container['departure_train_info'] = isset($data['departure_train_info']) ? $data['departure_train_info'] : null;
        $this->container['factsheet_id'] = isset($data['factsheet_id']) ? $data['factsheet_id'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['paxes'] = isset($data['paxes']) ? $data['paxes'] : null;
        $this->container['pickup_information'] = isset($data['pickup_information']) ? $data['pickup_information'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['rate_key'] = isset($data['rate_key']) ? $data['rate_key'] : null;
        $this->container['source_market_emergency_number'] = isset($data['source_market_emergency_number']) ? $data['source_market_emergency_number'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['transfer_details'] = isset($data['transfer_details']) ? $data['transfer_details'] : null;
        $this->container['transfer_type'] = isset($data['transfer_type']) ? $data['transfer_type'] : null;
        $this->container['vehicle'] = isset($data['vehicle']) ? $data['vehicle'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cancellation_policies'] === null) {
            $invalidProperties[] = "'cancellation_policies' can't be null";
        }
        if ($this->container['category'] === null) {
            $invalidProperties[] = "'category' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['links'] === null) {
            $invalidProperties[] = "'links' can't be null";
        }
        if ($this->container['pickup_information'] === null) {
            $invalidProperties[] = "'pickup_information' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['transfer_type'] === null) {
            $invalidProperties[] = "'transfer_type' can't be null";
        }
        $allowedValues = $this->getTransferTypeAllowableValues();
        if (!is_null($this->container['transfer_type']) && !in_array($this->container['transfer_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'transfer_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['vehicle'] === null) {
            $invalidProperties[] = "'vehicle' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets arrival_flight_number
     *
     * @return string
     */
    public function getArrivalFlightNumber()
    {
        return $this->container['arrival_flight_number'];
    }

    /**
     * Sets arrival_flight_number
     *
     * @param string $arrival_flight_number Arrival flight number
     *
     * @return $this
     */
    public function setArrivalFlightNumber($arrival_flight_number)
    {
        $this->container['arrival_flight_number'] = $arrival_flight_number;

        return $this;
    }

    /**
     * Gets arrival_ship_name
     *
     * @return string
     */
    public function getArrivalShipName()
    {
        return $this->container['arrival_ship_name'];
    }

    /**
     * Sets arrival_ship_name
     *
     * @param string $arrival_ship_name Arrival ship name
     *
     * @return $this
     */
    public function setArrivalShipName($arrival_ship_name)
    {
        $this->container['arrival_ship_name'] = $arrival_ship_name;

        return $this;
    }

    /**
     * Gets arrival_train_info
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\TrainInfo
     */
    public function getArrivalTrainInfo()
    {
        return $this->container['arrival_train_info'];
    }

    /**
     * Sets arrival_train_info
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\TrainInfo $arrival_train_info arrival_train_info
     *
     * @return $this
     */
    public function setArrivalTrainInfo($arrival_train_info)
    {
        $this->container['arrival_train_info'] = $arrival_train_info;

        return $this;
    }

    /**
     * Gets cancellation_policies
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\CancellationPolicy[]
     */
    public function getCancellationPolicies()
    {
        return $this->container['cancellation_policies'];
    }

    /**
     * Sets cancellation_policies
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\CancellationPolicy[] $cancellation_policies Cancellation policies
     *
     * @return $this
     */
    public function setCancellationPolicies($cancellation_policies)
    {
        $this->container['cancellation_policies'] = $cancellation_policies;

        return $this;
    }

    /**
     * Gets category
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\Category
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\Category $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets content
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\TransferServiceContent
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\TransferServiceContent $content content
     *
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets departure_flight_number
     *
     * @return string
     */
    public function getDepartureFlightNumber()
    {
        return $this->container['departure_flight_number'];
    }

    /**
     * Sets departure_flight_number
     *
     * @param string $departure_flight_number Departure flight number
     *
     * @return $this
     */
    public function setDepartureFlightNumber($departure_flight_number)
    {
        $this->container['departure_flight_number'] = $departure_flight_number;

        return $this;
    }

    /**
     * Gets departure_ship_name
     *
     * @return string
     */
    public function getDepartureShipName()
    {
        return $this->container['departure_ship_name'];
    }

    /**
     * Sets departure_ship_name
     *
     * @param string $departure_ship_name Departure ship name
     *
     * @return $this
     */
    public function setDepartureShipName($departure_ship_name)
    {
        $this->container['departure_ship_name'] = $departure_ship_name;

        return $this;
    }

    /**
     * Gets departure_train_info
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\TrainInfo
     */
    public function getDepartureTrainInfo()
    {
        return $this->container['departure_train_info'];
    }

    /**
     * Sets departure_train_info
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\TrainInfo $departure_train_info departure_train_info
     *
     * @return $this
     */
    public function setDepartureTrainInfo($departure_train_info)
    {
        $this->container['departure_train_info'] = $departure_train_info;

        return $this;
    }

    /**
     * Gets factsheet_id
     *
     * @return int
     */
    public function getFactsheetId()
    {
        return $this->container['factsheet_id'];
    }

    /**
     * Sets factsheet_id
     *
     * @param int $factsheet_id FactsheetId
     *
     * @return $this
     */
    public function setFactsheetId($factsheet_id)
    {
        $this->container['factsheet_id'] = $factsheet_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\Link[]
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\Link[] $links Links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets paxes
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\Pax[]
     */
    public function getPaxes()
    {
        return $this->container['paxes'];
    }

    /**
     * Sets paxes
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\Pax[] $paxes Paxes
     *
     * @return $this
     */
    public function setPaxes($paxes)
    {
        $this->container['paxes'] = $paxes;

        return $this;
    }

    /**
     * Gets pickup_information
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\PickupInformation
     */
    public function getPickupInformation()
    {
        return $this->container['pickup_information'];
    }

    /**
     * Sets pickup_information
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\PickupInformation $pickup_information pickup_information
     *
     * @return $this
     */
    public function setPickupInformation($pickup_information)
    {
        $this->container['pickup_information'] = $pickup_information;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\Price
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\Price $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets rate_key
     *
     * @return string
     */
    public function getRateKey()
    {
        return $this->container['rate_key'];
    }

    /**
     * Sets rate_key
     *
     * @param string $rate_key Rate Key
     *
     * @return $this
     */
    public function setRateKey($rate_key)
    {
        $this->container['rate_key'] = $rate_key;

        return $this;
    }

    /**
     * Gets source_market_emergency_number
     *
     * @return string
     */
    public function getSourceMarketEmergencyNumber()
    {
        return $this->container['source_market_emergency_number'];
    }

    /**
     * Sets source_market_emergency_number
     *
     * @param string $source_market_emergency_number Source market emergency number
     *
     * @return $this
     */
    public function setSourceMarketEmergencyNumber($source_market_emergency_number)
    {
        $this->container['source_market_emergency_number'] = $source_market_emergency_number;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Transfer status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets transfer_details
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\TransferDetail[]
     */
    public function getTransferDetails()
    {
        return $this->container['transfer_details'];
    }

    /**
     * Sets transfer_details
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\TransferDetail[] $transfer_details transfer details
     *
     * @return $this
     */
    public function setTransferDetails($transfer_details)
    {
        $this->container['transfer_details'] = $transfer_details;

        return $this;
    }

    /**
     * Gets transfer_type
     *
     * @return string
     */
    public function getTransferType()
    {
        return $this->container['transfer_type'];
    }

    /**
     * Sets transfer_type
     *
     * @param string $transfer_type Transfer Type
     *
     * @return $this
     */
    public function setTransferType($transfer_type)
    {
        $allowedValues = $this->getTransferTypeAllowableValues();
        if (!in_array($transfer_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'transfer_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['transfer_type'] = $transfer_type;

        return $this;
    }

    /**
     * Gets vehicle
     *
     * @return \EmanuelBuss\ApitudeTransfer\Model\Vehicle
     */
    public function getVehicle()
    {
        return $this->container['vehicle'];
    }

    /**
     * Sets vehicle
     *
     * @param \EmanuelBuss\ApitudeTransfer\Model\Vehicle $vehicle vehicle
     *
     * @return $this
     */
    public function setVehicle($vehicle)
    {
        $this->container['vehicle'] = $vehicle;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
