<?php
/**
 * TransferServiceBookingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EmanuelBuss\ApitudeTransfer
 * @author   Emanuel Karlsson <emanuel.karlsson@rolfsbuss.se>
 * @link     https://github.com/emanuelbuss/apitudetransfer
 */

/**
 * Transfer Booking API
 *
 * # APItude Transfer Booking API  APItude also includes now the ability to book transfers. This API will provide you with availability for transfer services and allow you to distribute those not only through the websites but also is thought to support mobile and tablets.  APItude for transfers API is designed to provide Hotelbeds Group clients with a set of API calls to:   * Enable the construction or creation of a complete transfer website or mobile application (app) * Integrate transfer services into existing systems both internal and external. * Integrate transfers contents for transfers into a common CMS for all the products being distributed.  **Transfer Booking API** provides all the needed calls (operations) to develop your booking funnel, confirm a booking and obtain the relevant information for a customer to enjoy the transfer service that he or she bought.  To obtain and cache the static content you can use [Transfers Cache API](), an API designed to return all the static information needed to operate the Transfers BookingAPI as quickly and simple as possible.
 *
 * OpenAPI spec version: 1.0
 * Contact: integrations.btb@hotelbeds.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/emanuelbuss/apitudetransfer
 * Please update the test case below to test the model.
 */

namespace EmanuelBuss\ApitudeTransfer;

/**
 * TransferServiceBookingTest Class Doc Comment
 *
 * @category    Class
 * @description The Transfer Service superclass
 * @package     EmanuelBuss\ApitudeTransfer
 * @author      Swagger Codegen team
 * @link        https://github.com/emanuelbuss/apitudetransfer
 */
class TransferServiceBookingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransferServiceBooking"
     */
    public function testTransferServiceBooking()
    {
    }

    /**
     * Test attribute "arrival_flight_number"
     */
    public function testPropertyArrivalFlightNumber()
    {
    }

    /**
     * Test attribute "arrival_ship_name"
     */
    public function testPropertyArrivalShipName()
    {
    }

    /**
     * Test attribute "arrival_train_info"
     */
    public function testPropertyArrivalTrainInfo()
    {
    }

    /**
     * Test attribute "cancellation_policies"
     */
    public function testPropertyCancellationPolicies()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "departure_flight_number"
     */
    public function testPropertyDepartureFlightNumber()
    {
    }

    /**
     * Test attribute "departure_ship_name"
     */
    public function testPropertyDepartureShipName()
    {
    }

    /**
     * Test attribute "departure_train_info"
     */
    public function testPropertyDepartureTrainInfo()
    {
    }

    /**
     * Test attribute "factsheet_id"
     */
    public function testPropertyFactsheetId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "paxes"
     */
    public function testPropertyPaxes()
    {
    }

    /**
     * Test attribute "pickup_information"
     */
    public function testPropertyPickupInformation()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "rate_key"
     */
    public function testPropertyRateKey()
    {
    }

    /**
     * Test attribute "source_market_emergency_number"
     */
    public function testPropertySourceMarketEmergencyNumber()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "transfer_details"
     */
    public function testPropertyTransferDetails()
    {
    }

    /**
     * Test attribute "transfer_type"
     */
    public function testPropertyTransferType()
    {
    }

    /**
     * Test attribute "vehicle"
     */
    public function testPropertyVehicle()
    {
    }
}
